colors:
  primary:
    background: '#15141b'
    foreground: '#edecee'

  cursor:
    cursor: '#a277ff'

  selection:
    text: CellForeground
    background: '#29263c'

  normal:
    black: '#110f18'
    red: '#ff6767'
    green: '#61ffca'
    yellow: '#ffca85'
    blue: '#a277ff'
    magenta: '#a277ff'
    cyan: '#61ffca'
    white: '#edecee'

  bright:
    black: '#4d4d4d'
    red: '#ff6767'
    green: '#61ffca'
    yellow: '#ffca85'
    blue: '#a277ff'
    magenta: '#a277ff'
    cyan: '#61ffca'
    white: '#edecee'

  search:
    matches:
      foreground: '#000000'
      background: '#ffffff'
    focused_match:
      foreground: '#ffffff'
      background: '#9F7AF5'

font:
  normal:
    family: 'SauceCodePro NerdFont Mono'
    style: Regular
  bold:
    family: 'SauceCodePro NerdFont Mono'
    style: Regular
  italic:
    family: 'SauceCodePro NerdFont Mono'
    style: Italic
  bold_italic:
    family: 'SauceCodePro NerdFont Mono'
    style: Italic

  size: 12.0
  offset:
    x: 0
    y: 9
  glyph_offset:
    x: 0
    y: 3

window:
  padding:
    x: 10
    y: 12
  decorations: none
  dimensions:
    columns: 520
    lines: 25

scrolling:
  history: 100000
  multiplier: 4

cursor:
  style:
    shape: Beam

draw_bold_text_with_bright_colors: false

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

key_bindings:
  - { key: R, mods: Command, mode: ~Vi|~Search, chars: "\x0c" }
  # - { key: R, mods: Command, mode: ~Vi|~Search, action: ClearHistory }
  - { key: W, mods: Command, action: Hide }
  - { key: W, mods: Command|Shift, action: Quit }
  - { key: N, mods: Command, action: SpawnNewInstance }
  - { key: T, mods: Command, action: CreateNewWindow }
  - { key: Left, mods: Alt, chars: "\x1bb" } # Skip word left
  - { key: Right, mods: Alt, chars: "\x1bf" } # Skip word right
  - { key: Left, mods: Command, chars: "\x01" } # Home
  - { key: Right, mods: Command, chars: "\x05" } # End
  - { key: Back, mods: Command, chars: "\x15" } # Delete line
  - { key: Back, mods: Alt, chars: "\x1b\x7f" } # Delete word

shell:
  program: /bin/fish
  args:
    # login
    - -l
    - -c
    - 'zellij attach --index 0 --create'
